[tool.poetry]
name = "robo-ragmond"
version = "0.1.0"
description = "A RAG-based customer support chatbot for Tampa Bay Rays"
authors = ["Jarred Robidoux & Yuki Taketani"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
chromadb = ">=0.4.0"
sentence-transformers = ">=2.2.0"
python-dotenv = ">=1.0.0"
torch = ">=2.0.0"
crawl4ai = ">=0.1.0"
tqdm = ">=4.65.0"
langchain_core = "*"
langchain_anthropic = ">=0.3.0,<0.4.0"
streamlit = "*"
asyncio = ">=3.4.3"
aiohttp = ">=3.8.0"
beautifulsoup4 = ">=4.9.3"
markdown = ">=3.3.4"
huggingface-hub = ">=0.19.0"
transformers = ">=4.36.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"